SELECT a.PRODUCT_ID, a.PRODUCT_NAME, sum(AMOUNT*PRICE) as TOTAL_SALES
from FOOD_PRODUCT a , FOOD_ORDER b 
where a.PRODUCT_ID=b.PRODUCT_ID
and PRODUCE_DATE like '2022-05%'
group by PRODUCT_ID
order by TOTAL_SALES desc,a.PRODUCT_ID