SELECT DISTINCT CAR_ID 
FROM  CAR_RENTAL_COMPANY_CAR  
WHERE CAR_ID IN (SELECT CAR_ID 
                FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                WHERE TO_CHAR(START_DATE,'MM') = '10')
AND CAR_TYPE = '세단'
ORDER BY CAR_ID DESC;