SELECT DISTINCT A.CAR_ID 
FROM  CAR_RENTAL_COMPANY_CAR A ,CAR_RENTAL_COMPANY_RENTAL_HISTORY B
WHERE A.CAR_ID = B.CAR_ID
AND TO_CHAR(START_DATE,'YYYYMM') = '202210'
AND CAR_TYPE = '세단'
ORDER BY A.CAR_ID DESC;